name: dbt-ci

on:
  push:
    branches:
      - main

jobs:
  dbt:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt

          echo "
          ga4_analytics:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: oauth
                project: dummy-project
                dataset: dummy_dataset
                threads: 1
                location: US
          " > ~/.dbt/profiles.yml

      - name: Check profile exists
        run: |
          ls -la ~/.dbt
          cat ~/.dbt/profiles.yml

      - name: dbt deps
        run: dbt deps

      - name: dbt parse
        run: dbt parse
